name = "spacegamedev"
# Set this to today's date
compatibility_date = "2026-06-25"
preview_urls = true

[assets]
directory = "./dist/"
pages_build_output_dir = "./dist"
not_found_handling = "404-page"